name: Deploy to EC2

env:
  REMOTE_DIR: /home/ubuntu/appflowy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Setup remote environment
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'ENDSSH'
          # Create directory with proper permissions
          sudo rm -rf ${{ env.REMOTE_DIR }}
          sudo mkdir -p ${{ env.REMOTE_DIR }}
          sudo chown ubuntu:ubuntu ${{ env.REMOTE_DIR }}
          
          # Setup docker
          sudo groupadd -f docker
          sudo usermod -aG docker ubuntu
          sudo chmod 666 /var/run/docker.sock
          ENDSSH

      - name: Copy files
        run: |
          # Copy project files
          scp -i ~/.ssh/id_rsa -r ./docker ubuntu@${{ secrets.EC2_HOST }}:${{ env.REMOTE_DIR }}/
          scp -i ~/.ssh/id_rsa -r ./nginx ubuntu@${{ secrets.EC2_HOST }}:${{ env.REMOTE_DIR }}/
          scp -i ~/.ssh/id_rsa docker-compose.yml ubuntu@${{ secrets.EC2_HOST }}:${{ env.REMOTE_DIR }}/
          
          # Create and copy environment file
          echo "${{ secrets.EC2_ENV }}" > .env
          scp -i ~/.ssh/id_rsa .env ubuntu@${{ secrets.EC2_HOST }}:${{ env.REMOTE_DIR }}/

      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'ENDSSH'
          cd ${{ env.REMOTE_DIR }}
          
          # Set proper permissions for nginx files
          sudo chown -R ubuntu:ubuntu nginx
          sudo chmod -R 755 nginx
          
          # Ensure SSL directory exists with proper permissions
          sudo mkdir -p nginx/ssl
          sudo chown -R ubuntu:ubuntu nginx/ssl
          sudo chmod -R 600 nginx/ssl
          
          # Start containers
          docker-compose down --remove-orphans
          docker-compose up -d
          
          # Verify deployment
          sleep 10
          if docker-compose ps | grep -q "Exit"; then
            echo "Some containers failed to start"
            docker-compose logs
            exit 1
          fi
          ENDSSH

      - name: Cleanup
        if: always()
        run: |
          rm -f ~/.ssh/id_rsa
          rm -f .env
